project:
  type: website
  output-dir: docs

website:
  title: "Comic Book Research Lab"
  navbar:
    background: white
    left:
      - text: "Research"
        href: research.qmd
      - text: "Appraisal"
        href: appraisal.qmd
      - text: "Resources"
        href: resources.qmd
      - text: "About"
        href: about.qmd
page-footer:
    center: "© 2025 Comic Book Research Lab — All Rights Reserved"
    background: "#B3D5E5"


format:
  html:
    theme: cosmo
    css: styles.css
    page-layout: full

