project:
  type: website

website:
  title: "Comic Book Research Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: Blog
      - href: contact.qmd
        text: Contact
  page-footer:
    center: "© 2025 Comic Book Research Lab — All Rights Reserved"
    background: light

format:
  html:
    theme: default
    css: styles.css
