project:
  type: website
  output-dir: docs

website:
  title: "Comic Book Research Lab"
  favicon: images/logo-circle.png

  # Top navbar: logo appears left (brand), links on the right.
  navbar:
    left:
      - icon: images/logo-circle.png
        href: index.qmd
        text: "Comic Book Research Lab"
    right:
      - text: "Research"
        href: research/index.qmd
      - text: "Appraisal"
        href: appraisal/index.qmd
      - text: "Resources"
        href: resources/index.qmd
      - text: "About"
        href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

# Optional: site metadata useful for search/sharing
site-url: "https://jpkelley.github.io/comicbookresearchlab"
description: "Research and resources about comic books and collecting."

# Keep _quarto.yml small — most layout is in index.qmd + styles.css
